import type { LearnModule, LevelNode, Quest, ProgressData, PracticeQuestion } from './types';

export const LEVELS: LevelNode[] = [
  { id: 1, name: 'Bead Basics', nameAr: 'الخرزات الأساسية', status: 'completed', icon: 'Circle', xpRequired: 0 },
  { id: 2, name: 'Counting 1-9', nameAr: 'العد ١-٩', status: 'completed', icon: 'Hash', xpRequired: 50 },
  { id: 3, name: 'Tens & Ones', nameAr: 'العشرات والآحاد', status: 'completed', icon: 'Sigma', xpRequired: 150 },
  { id: 4, name: 'Addition Magic', nameAr: 'سحر الجمع', status: 'available', icon: 'Plus', xpRequired: 300 },
  { id: 5, name: 'Subtraction Quest', nameAr: 'رحلة الطرح', status: 'locked', icon: 'Minus', xpRequired: 500 },
  { id: 6, name: 'Anzan Beginner', nameAr: 'الأنزان للمبتدئين', status: 'locked', icon: 'Eye', xpRequired: 800 },
  { id: 7, name: 'Mental Master', nameAr: 'خبير الذهني', status: 'locked', icon: 'Brain', xpRequired: 1200 },
  { id: 8, name: 'Speed Champion', nameAr: 'بطل السرعة', status: 'locked', icon: 'Zap', xpRequired: 1800 },
];

export const LEARN_MODULES: LearnModule[] = [
  {
    id: 1,
    title: 'Meet the Soroban',
    titleAr: 'تعرف على السوروبان',
    description: 'Discover the parts of the Japanese abacus',
    descriptionAr: 'اكتشف أجزاء العداد الياباني',
    status: 'completed',
    beads: { upper: 0, lower: 0 },
    value: 0,
    concept: 'The Soroban has a top deck (heaven) and bottom deck (earth)',
    conceptAr: 'السوروبان يحتوي على قسم علوي (السماء) وقسم سفلي (الأرض)',
    icon: 'Info',
  },
  {
    id: 2,
    title: 'Heaven Bead',
    titleAr: 'خرزة السماء',
    description: 'The top bead is worth 5',
    descriptionAr: 'الخرزة العلوية قيمتها ٥',
    status: 'completed',
    beads: { upper: 1, lower: 0 },
    value: 5,
    concept: 'One upper bead activated = 5',
    conceptAr: 'تفعيل خرزة علوية واحدة = ٥',
    icon: 'Star',
  },
  {
    id: 3,
    title: 'Earth Beads',
    titleAr: 'خرزات الأرض',
    description: 'Each bottom bead is worth 1',
    descriptionAr: 'كل خرزة سفلية قيمتها ١',
    status: 'completed',
    beads: { upper: 0, lower: 3 },
    value: 3,
    concept: 'Three lower beads activated = 3',
    conceptAr: 'تفعيل ثلاث خرزات سفلية = ٣',
    icon: 'CircleDot',
  },
  {
    id: 4,
    title: 'Combining Beads',
    titleAr: 'دمج الخرزات',
    description: 'Mix upper and lower beads',
    descriptionAr: 'امزج الخرزات العلوية والسفلية',
    status: 'available',
    beads: { upper: 1, lower: 2 },
    value: 7,
    concept: 'Upper (5) + Lower (2) = 7',
    conceptAr: 'علوي (٥) + سفلي (٢) = ٧',
    icon: 'Combine',
  },
  {
    id: 5,
    title: 'Counting to 9',
    titleAr: 'العد حتى ٩',
    description: 'Maximum value on one column',
    descriptionAr: 'القيمة القصوى في عمود واحد',
    status: 'locked',
    beads: { upper: 1, lower: 4 },
    value: 9,
    concept: 'Upper (5) + Lower (4) = 9',
    conceptAr: 'علوي (٥) + سفلي (٤) = ٩',
    icon: 'Hash',
  },
  {
    id: 6,
    title: 'Two-Digit Numbers',
    titleAr: 'الأرقام ذات خانتين',
    description: 'Using the tens column',
    descriptionAr: 'استخدام عمود العشرات',
    status: 'locked',
    beads: { upper: 0, lower: 4 },
    value: 40,
    concept: 'Tens column + ones column = two-digit numbers',
    conceptAr: 'عمود العشرات + عمود الآحاد = أرقام ذات خانتين',
    icon: 'Sigma',
  },
  // ========== دروس الجمع الأساسية ==========
  {
    id: 7,
    title: 'Simple Addition',
    titleAr: 'الجمع البسيط',
    description: 'Add beads directly without carrying',
    descriptionAr: 'أضف الخرزات مباشرة دون حمل',
    status: 'locked',
    beads: { upper: 0, lower: 5 },
    value: 5,
    concept: 'Simple addition: add lower beads directly. Example: 3 + 2 = 5',
    conceptAr: 'الجمع البسيط: أضف خرزات سفلية مباشرة. مثال: ٣ + ٢ = ٥',
    icon: 'Plus',
  },
  {
    id: 8,
    title: 'Adding 5',
    titleAr: 'الجمع مع أصدقاء 5',
    description: 'Use the upper bead to add',
    descriptionAr: 'استخدم الخرزة العلوية في الجمع',
    status: 'locked',
    beads: { upper: 1, lower: 2 },
    value: 7,
    concept: 'When adding, sometimes use the upper bead. Example: 4 + 3 = 7',
    conceptAr: 'عند الجمع، أحياناً نستخدم الخرزة العلوية. مثال: ٤ + ٣ = ٧',
    icon: 'Plus',
  },
  {
    id: 9,
    title: 'Adding 10',
    titleAr: 'الجمع مع أصدقاء 10',
    description: 'Carry to the tens column',
    descriptionAr: 'احمل إلى عمود العشرات',
    status: 'locked',
    beads: { upper: 1, lower: 2 },
    value: 12,
    concept: 'When adding exceeds 9, carry 10 to the next column. Example: 7 + 5 = 12',
    conceptAr: 'عند تجاوز الجمع للعدد ٩، احمل ١٠ إلى العمود التالي. مثال: ٧ + ٥ = ١٢',
    icon: 'Plus',
  },
  // ========== دروس الطرح ==========
  {
    id: 10,
    title: 'Simple Subtraction',
    titleAr: 'الطرح البسيط',
    description: 'Remove beads to subtract',
    descriptionAr: 'أزل الخرزات لإتمام عملية الطرح',
    status: 'locked',
    beads: { upper: 0, lower: 3 },
    value: 3,
    concept: 'Simple subtraction: remove lower beads directly. Example: 5 - 2 = 3',
    conceptAr: 'الطرح البسيط: أزل خرزات سفلية مباشرة. مثال: ٥ - ٢ = ٣',
    icon: 'Minus',
  },
  {
    id: 11,
    title: 'Subtracting 5',
    titleAr: 'الطرح مع أصدقاء 5',
    description: 'Use the upper bead to subtract',
    descriptionAr: 'استخدم الخرزة العلوية في الطرح',
    status: 'locked',
    beads: { upper: 0, lower: 4 },
    value: 4,
    concept: 'When subtracting, sometimes we need to remove 5 and add back. Example: 7 - 3 = 4',
    conceptAr: 'عند الطرح، أحياناً نحتاج لإزالة 5 وإرجاع الباقي. مثال: ٧ - ٣ = ٤',
    icon: 'Minus',
  },
  {
    id: 12,
    title: 'Subtracting 10',
    titleAr: 'الطرح مع أصدقاء 10',
    description: 'Borrow from the tens column',
    descriptionAr: 'استلف من عمود العشرات',
    status: 'locked',
    beads: { upper: 0, lower: 2 },
    value: 7,
    concept: 'When subtracting more than available, borrow 10 from the next column. Example: 12 - 5 = 7',
    conceptAr: 'عند طرح رقم أكبر من المتوفر، استلف 10 من العمود التالي. مثال: ١٢ - ٥ = ٧',
    icon: 'Minus',
  },
];

export const QUESTS: Quest[] = [
  {
    id: 1,
    title: 'Daily Practice',
    titleAr: 'التدريب اليومي',
    description: 'Complete 10 practice problems',
    descriptionAr: 'أكمل ١٠ مسائل تدريبية',
    xpReward: 50,
    progress: 4,
    target: 10,
    icon: 'Swords',
    color: 'from-purple-500 to-electric-500',
  },
  {
    id: 2,
    title: 'Anzan Apprentice',
    titleAr: 'متدرب الأنزان',
    description: 'Score 20 points in Anzan Flash',
    descriptionAr: 'احصل على ٢٠ نقطة في الأنزان',
    xpReward: 80,
    progress: 12,
    target: 20,
    icon: 'Eye',
    color: 'from-electric-500 to-emerald2-500',
  },
  {
    id: 3,
    title: 'Perfect Streak',
    titleAr: 'سلسلة مثالية',
    description: 'Answer 5 in a row correctly',
    descriptionAr: 'أجب على ٥ أسئلة متتالية بشكل صحيح',
    xpReward: 100,
    progress: 2,
    target: 5,
    icon: 'Flame',
    color: 'from-gold-400 to-gold-600',
  },
  {
    id: 4,
    title: 'Lesson Explorer',
    titleAr: 'مستكشف الدروس',
    description: 'Complete 3 learning modules',
    descriptionAr: 'أكمل ٣ وحدات تعليمية',
    xpReward: 60,
    progress: 3,
    target: 3,
    icon: 'BookOpen',
    color: 'from-emerald2-400 to-emerald2-600',
  },
];

// ============================================================
// أسئلة التدريب المنظمة (جمع وطرح منفصلان)
// ============================================================

export const ADDITION_QUESTIONS: PracticeQuestion[] = [
  { question: '٣ + ٢', answer: 5, choices: [4, 5, 6, 7] },
  { question: '٧ + ١', answer: 8, choices: [6, 7, 8, 9] },
  { question: '٤ + ٤', answer: 8, choices: [7, 8, 9, 10] },
  { question: '٦ + ٥', answer: 11, choices: [10, 11, 12, 13] },
  { question: '٣ + ٦', answer: 9, choices: [8, 9, 10, 11] },
  { question: '٥ + ٥', answer: 10, choices: [9, 10, 11, 12] },
  { question: '٢ + ٧', answer: 9, choices: [8, 9, 10, 11] },
  { question: '١ + ٨', answer: 9, choices: [8, 9, 10, 11] },
  { question: '٦ + ٣', answer: 9, choices: [8, 9, 10, 11] },
  { question: '٤ + ٥', answer: 9, choices: [8, 9, 10, 11] },
];

export const SUBTRACTION_QUESTIONS: PracticeQuestion[] = [
  { question: '٩ - ٣', answer: 6, choices: [5, 6, 7, 8] },
  { question: '٨ - ٢', answer: 6, choices: [4, 5, 6, 7] },
  { question: '١٢ - ٤', answer: 8, choices: [7, 8, 9, 10] },
  { question: '١٥ - ٧', answer: 8, choices: [6, 7, 8, 9] },
  { question: '١٠ - ٥', answer: 5, choices: [4, 5, 6, 7] },
  { question: '٧ - ٣', answer: 4, choices: [3, 4, 5, 6] },
  { question: '١٤ - ٦', answer: 8, choices: [7, 8, 9, 10] },
  { question: '١١ - ٥', answer: 6, choices: [5, 6, 7, 8] },
  { question: '١٣ - ٤', answer: 9, choices: [8, 9, 10, 11] },
  { question: '١٦ - ٨', answer: 8, choices: [7, 8, 9, 10] },
];

// للتوافق مع الكود القديم
export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  ...ADDITION_QUESTIONS,
  ...SUBTRACTION_QUESTIONS,
];

export const PROGRESS_DATA: ProgressData = {
  totalProblems: 247,
  correctAnswers: 198,
  averageSpeed: 4.2,
  lessonsCompleted: 3,
  anzanHighScore: 42,
  weeklyXP: [
    { day: 'السبت', xp: 120 },
    { day: 'الأحد', xp: 85 },
    { day: 'الاثنين', xp: 150 },
    { day: 'الثلاثاء', xp: 60 },
    { day: 'الأربعاء', xp: 200 },
    { day: 'الخميس', xp: 175 },
    { day: 'الجمعة', xp: 90 },
  ],
};

// ============================================================
// الشارات (Badges)
// ============================================================

export const BADGES = [
  {
    id: 'beginner',
    name: 'Beginner',
    nameAr: 'مبتدئ',
    xpRequired: 50,
    icon: 'Star',
  },
  {
    id: 'anzan-master',
    name: 'Anzan Master',
    nameAr: 'سيد الأنزان',
    xpRequired: 100,
    icon: 'Eye',
  },
  {
    id: 'soroban-expert',
    name: 'Soroban Expert',
    nameAr: 'خبير السوروبان',
    xpRequired: 200,
    icon: 'Award',
  },
  {
    id: 'legend',
    name: 'Legend',
    nameAr: 'أسطورة',
    xpRequired: 500,
    icon: 'Crown',
  },
];
