import type { LearnModule, LevelNode, Quest, ProgressData, PracticeQuestion } from './types';

export const LEVELS: LevelNode[] = [
  { id: 1, name: 'Bead Basics', nameAr: 'الخرزات الأساسية', status: 'completed', icon: 'Circle', xpRequired: 0 },
  { id: 2, name: 'Counting 1-9', nameAr: 'العد ١-٩', status: 'completed', icon: 'Hash', xpRequired: 50 },
  { id: 3, name: 'Tens & Ones', nameAr: 'العشرات والآحاد', status: 'completed', icon: 'Sigma', xpRequired: 150 },
  { id: 4, name: 'Addition Magic', nameAr: 'سحر الجمع', status: 'available', icon: 'Plus', xpRequired: 300 },
  { id: 5, name: 'Subtraction Quest', nameAr: 'رحلة الطرح', status: 'locked', icon: 'Minus', xpRequired: 500 },
  { id: 6, name: 'Multiplication', nameAr: 'الضرب', status: 'locked', icon: 'X', xpRequired: 800 },
  { id: 7, name: 'Division', nameAr: 'القسمة', status: 'locked', icon: 'Divide', xpRequired: 1200 },
  { id: 8, name: 'Anzan Beginner', nameAr: 'الأنزان للمبتدئين', status: 'locked', icon: 'Eye', xpRequired: 1800 },
];

export const LEARN_MODULES: LearnModule[] = [
  {
    id: 1,
    title: 'Meet the Soroban',
    titleAr: 'تعرف على السوروبان',
    description: 'Discover the parts',
    descriptionAr: 'اكتشف أجزاء العداد الياباني',
    status: 'available',
    beads: { upper: 0, lower: 0 },
    value: 0,
    concept: 'Top deck and bottom deck',
    conceptAr: 'السوروبان يحتوي على قسم علوي (السماء) وقسم سفلي (الأرض)',
    icon: 'Info',
    audioText: 'مرحباً بك في عالم السوروبان! السوروبان هو عداد ياباني قديم، يساعدنا على الحساب بسرعة كبيرة. يتكون من عمود رأسي، وقسمين: القسم العلوي ويسمى السماء، والقسم السفلي ويسمى الأرض. هيا بنا نتعلم معاً!',
    rule: 'Use the thumb for lower beads up, and index finger for upper bead and lower beads down',
    ruleAr: 'قاعدة الإصبعين: الإبهام يرفع الخرزات السفلية، والسبابة تنزل الخرزة العلوية والخرزات السفلية',
    examples: [
      {
        question: 'شاهد: كل الخرزات بعيدة عن العارضة → القيمة ٠',
        targetValue: 0,
        type: 'direct',
        steps: [],
        explanation: 'عندما تكون كل الخرزات بعيدة عن العارضة، القيمة = ٠',
      },
      {
        question: 'مثّل الرقم ٠ على المعداد',
        targetValue: 0,
        type: 'direct',
        steps: [],
        explanation: 'اترك كل الخرزات بعيدة عن العارضة. أحسنت!',
      },
      {
        question: 'شاهد: نرفع خرزة سفلية واحدة بالإبهام → القيمة ١',
        targetValue: 1,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'ارفع خرزة سفلية واحدة بالإبهام' },
        ],
        explanation: 'كل خرزة سفلية = ١. نرفعها بالإبهام.',
      },
      {
        question: 'مثّل الرقم ٢ على المعداد',
        targetValue: 2,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع خرزتين سفليتين بالإبهام' },
        ],
        explanation: 'ارفع خرزتين سفليتين بالإبهام',
      },
    ],
  },
  {
    id: 2,
    title: 'Heaven Bead',
    titleAr: 'خرزة السماء',
    description: 'Top bead worth 5',
    descriptionAr: 'الخرزة العلوية قيمتها ٥',
    status: 'locked',
    beads: { upper: 1, lower: 0 },
    value: 5,
    concept: 'Upper bead = 5',
    conceptAr: 'تفعيل خرزة علوية واحدة = ٥',
    icon: 'Star',
    audioText: 'خرزة السماء هي الخرزة الذهبية في الأعلى. عندما ننزلها لتلامس العارضة، تصبح قيمتها خمسة. نستخدم السبابة فقط لتحريكها. هيا نجرب معاً!',
    rule: 'Use index finger ONLY to move upper bead',
    ruleAr: 'الخرزة العلوية تُحرَّك بالسبابة فقط، لا يلمسها الإبهام أبداً',
    examples: [
      {
        question: 'شاهد: ننزل الخرزة العلوية بالسبابة → القيمة ٥',
        targetValue: 5,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', upperBead: true, finger: 'index', explanation: 'نزّل الخرزة العلوية بالسبابة' },
        ],
        explanation: 'الخرزة العلوية = ٥، تُحرَّك بالسبابة فقط',
      },
      {
        question: 'مثّل الرقم ٥ على المعداد',
        targetValue: 5,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', upperBead: true, finger: 'index', explanation: 'نزّل الخرزة العلوية بالسبابة' },
        ],
        explanation: 'نزّل الخرزة العلوية بالسبابة',
      },
      {
        question: 'مثّل الرقم ٦ على المعداد',
        targetValue: 6,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'أنزل الخرزة العلوية (٥) بالسبابة، وارفع خرزة سفلية (١) بالإبهام' },
        ],
        explanation: '٥ + ١ = ٦، حركة القبض: العلوية بالسبابة، والسفلية بالإبهام',
      },
      {
        question: 'مثّل الرقم ٧ على المعداد',
        targetValue: 7,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'أنزل الخرزة العلوية بالسبابة، وارفع خرزتين سفليتين بالإبهام' },
        ],
        explanation: '٥ + ٢ = ٧',
      },
    ],
  },
  {
    id: 3,
    title: 'Earth Beads',
    titleAr: 'خرزات الأرض',
    description: 'Each bottom bead = 1',
    descriptionAr: 'كل خرزة سفلية قيمتها ١',
    status: 'locked',
    beads: { upper: 0, lower: 3 },
    value: 3,
    concept: 'Each lower bead = 1',
    conceptAr: 'كل خرزة سفلية = ١',
    icon: 'CircleDot',
    audioText: 'خرزات الأرض هي الخرزات الزرقاء في الأسفل. كل خرزة منها تساوي واحداً. عندما نرفعها لتلامس العارضة بالإبهام، نضيف واحداً إلى القيمة. هيا نجرب!',
    rule: 'Use thumb to raise lower beads, index to lower them',
    ruleAr: 'الإبهام يرفع الخرزات السفلية، والسبابة تنزلها',
    examples: [
      {
        question: 'شاهد: ارفع خرزة سفلية بالإبهام → القيمة ١',
        targetValue: 1,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'ارفع خرزة سفلية بالإبهام' },
        ],
        explanation: 'خرزة سفلية واحدة = ١',
      },
      {
        question: 'مثّل الرقم ٢',
        targetValue: 2,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع خرزتين سفليتين بالإبهام' },
        ],
        explanation: '٢ = خرزتان سفليتان',
      },
      {
        question: 'مثّل الرقم ٣',
        targetValue: 3,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 3, finger: 'thumb', explanation: 'ارفع ٣ خرزات سفليّة بالإبهام' },
        ],
        explanation: '٣ = ٣ خرزات سفلية',
      },
      {
        question: 'مثّل الرقم ٤',
        targetValue: 4,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤ خرزات سفلية بالإبهام' },
        ],
        explanation: '٤ = ٤ خرزات سفلية. أحسنت!',
      },
    ],
  },
  {
    id: 4,
    title: 'Combining Beads',
    titleAr: 'دمج الخرزات',
    description: 'Mix upper and lower',
    descriptionAr: 'امزج الخرزات العلوية والسفلية',
    status: 'locked',
    beads: { upper: 1, lower: 2 },
    value: 7,
    concept: 'Upper (5) + Lower (2) = 7',
    conceptAr: 'علوي (٥) + سفلي (٢) = ٧',
    icon: 'Combine',
    audioText: 'الآن سنتعلم كيف نجمع بين الخرزة العلوية والخرزات السفلية. الخرزة العلوية تساوي خمسة، وكل خرزة سفلية تساوي واحداً. نستخدم السبابة للعلوية والإبهام للسفلية في نفس الوقت. هيا نجرب!',
    rule: 'Pinch movement: index lowers upper bead while thumb raises lower beads',
    ruleAr: 'حركة القبض: السبابة تنزل الخرزة العلوية والإبهام يرفع الخرزات السفلية في نفس الوقت',
    examples: [
      {
        question: 'مثّل الرقم ٦',
        targetValue: 6,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'أنزل الخرزة العلوية بالسبابة، وارفع خرزة سفلية بالإبهام' },
        ],
        explanation: '٥ + ١ = ٦',
      },
      {
        question: 'مثّل الرقم ٧',
        targetValue: 7,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'أنزل الخرزة العلوية بالسبابة، وارفع خرزتين سفليتين بالإبهام' },
        ],
        explanation: '٥ + ٢ = ٧',
      },
      {
        question: 'مثّل الرقم ٨',
        targetValue: 8,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 3, finger: 'both', explanation: 'أنزل الخرزة العلوية بالسبابة، وارفع ٣ خرزات سفلية بالإبهام' },
        ],
        explanation: '٥ + ٣ = ٨',
      },
    ],
  },
  {
    id: 5,
    title: 'Counting to 9',
    titleAr: 'العد حتى ٩',
    description: 'Max value on one column',
    descriptionAr: 'القيمة القصوى في عمود واحد',
    status: 'locked',
    beads: { upper: 1, lower: 4 },
    value: 9,
    concept: 'Upper (5) + Lower (4) = 9',
    conceptAr: 'علوي (٥) + سفلي (٤) = ٩',
    icon: 'Hash',
    audioText: 'الآن سنتعلم العد حتى الرقم تسعة. عندما نرفع كل الخرزات السفلية الأربع بالإبهام، وننزل الخرزة العلوية بالسبابة، نحصل على القيمة تسعة. وهي أكبر قيمة في عمود واحد. هيا نجرب!',
    rule: 'Maximum value on one column is 9 (5 + 4)',
    ruleAr: 'أقصى قيمة في عمود واحد هي ٩ (٥ + ٤)',
    examples: [
      {
        question: 'مثّل الرقم ٧',
        targetValue: 7,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'العلوية + خرزتان سفليتان' },
        ],
        explanation: '٥ + ٢ = ٧',
      },
      {
        question: 'مثّل الرقم ٨',
        targetValue: 8,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 3, finger: 'both', explanation: 'العلوية + ٣ سفليّة' },
        ],
        explanation: '٥ + ٣ = ٨',
      },
      {
        question: 'مثّل الرقم ٩',
        targetValue: 9,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 4, finger: 'both', explanation: 'العلوية + ٤ سفليّة' },
        ],
        explanation: '٥ + ٤ = ٩ (القيمة القصوى)',
      },
      {
        question: 'شاهد: ٩ + ١ = ؟ (نحمل إلى العشرات)',
        targetValue: 10,
        type: 'big-friend',
        steps: [
          { movement: 'small-friend', upperBead: false, lowerBeads: 0, finger: 'both', explanation: 'نضيف ١٠ في عمود العشرات، ونزيل ٩ من الآحاد' },
        ],
        explanation: '٩ + ١ = ١٠. نحمل ١٠ إلى عمود العشرات',
      },
    ],
  },
  {
    id: 6,
    title: 'Two-Digit Numbers',
    titleAr: 'الأرقام ذات خانتين',
    description: 'Using the tens column',
    descriptionAr: 'استخدام عمود العشرات',
    status: 'locked',
    beads: { upper: 0, lower: 4 },
    value: 40,
    concept: 'Tens column = ×10',
    conceptAr: 'عمود العشرات = ×١٠',
    icon: 'Sigma',
    audioText: 'الآن سنتعلم الأرقام ذات خانتين. عمود العشرات يساوي عشرة أضعاف عمود الآحاد. نبدأ دائماً من اليسار إلى اليمين. هيا نجرب!',
    rule: 'Start from the LARGEST column (left) to the smallest (right)',
    ruleAr: 'نبدأ الحساب من العمود الأكبر (يسار) إلى الأصغر (يمين)',
    examples: [
      {
        question: 'مثّل الرقم ١٠',
        targetValue: 10,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'ارفع خرزة واحدة في عمود العشرات بالإبهام' },
        ],
        explanation: 'خرزة واحدة في العشرات = ١٠',
      },
      {
        question: 'مثّل الرقم ٢٥',
        targetValue: 25,
        type: 'pinch',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع خرزتين في عمود العشرات' },
          { movement: 'pinch', upperBead: true, lowerBeads: 0, finger: 'both', explanation: 'في الآحاد: أنزل الخرزة العلوية' },
        ],
        explanation: '٢ في العشرات + ٥ في الآحاد = ٢٥',
      },
      {
        question: 'مثّل الرقم ٤٠',
        targetValue: 40,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤ خرزات في عمود العشرات' },
        ],
        explanation: '٤ في العشرات = ٤٠',
      },
    ],
  },
  {
    id: 7,
    title: 'Simple Addition',
    titleAr: 'الجمع البسيط',
    description: 'Add beads directly',
    descriptionAr: 'أضف الخرزات مباشرة دون حمل',
    status: 'locked',
    beads: { upper: 0, lower: 5 },
    value: 5,
    concept: '3 + 2 = 5',
    conceptAr: 'الجمع البسيط: أضف خرزات سفلية مباشرة',
    icon: 'Plus',
    audioText: 'الآن سنتعلم الجمع البسيط. عندما نجمع رقمين صغيرين، نرفع خرزات إضافية على المعداد بالإبهام. مثلاً، ثلاثة زائد اثنين يساوي خمسة. هيا نجرب معاً!',
    rule: 'Direct addition: use thumb to raise lower beads',
    ruleAr: 'الجمع المباشر: الإبهام يرفع الخرزات السفلية',
    examples: [
      {
        question: '٢ + ٣ = ؟',
        targetValue: 5,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع خرزتين للإشارة إلى ٢' },
          { movement: 'raise-lower', lowerBeads: 3, finger: 'thumb', explanation: 'ارفع ٣ خرزات أخرى للإضافة' },
        ],
        explanation: '٢ + ٣ = ٥',
      },
      {
        question: '١ + ٤ = ؟',
        targetValue: 5,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'ارفع خرزة للإشارة إلى ١' },
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤ خرزات أخرى' },
        ],
        explanation: '١ + ٤ = ٥',
      },
      {
        question: '٣ + ٤ = ؟',
        targetValue: 7,
        type: 'small-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 3, finger: 'thumb', explanation: 'ارفع ٣ خرزات للإشارة إلى ٣' },
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: '٤ لا يمكن رفعها. استخدم قاعدة صديق ٤: أنزل العلوية + ارفع ٢ سفليّة (٥ - ٢ = ٣)' },
        ],
        explanation: '٣ + ٤ = ٧. صديق ٤ هو ١، لكن لأن الخرزات السفلية لا تكفي، نستخدم العلوية',
      },
    ],
  },
  {
    id: 8,
    title: 'Adding 5',
    titleAr: 'الجمع مع أصدقاء 5',
    description: 'Use upper bead to add',
    descriptionAr: 'استخدم الخرزة العلوية في الجمع',
    status: 'locked',
    beads: { upper: 1, lower: 2 },
    value: 7,
    concept: '4 + 3 = 7',
    conceptAr: 'عند الجمع، أحياناً نستخدم الخرزة العلوية',
    icon: 'Plus',
    audioText: 'أحياناً عندما نجمع، نحتاج لاستخدام الخرزة العلوية. مثلاً، أربعة زائد ثلاثة. لا يمكن أن نرفع ثلاث خرزات سفلية، لأن الحد الأقصى أربع. لذا نستخدم الخرزة العلوية. صديق ٣ هو ٢، أي ٥ - ٢ = ٣. هيا نجرب!',
    rule: 'Small Friend: if adding N exceeds 4, use upper bead (5) and subtract (5 - N)',
    ruleAr: 'صديق صغير: إذا تجاوز الجمع ٤، استخدم العلوية (٥) واطرح (٥ - N)',
    examples: [
      {
        question: '٤ + ١ = ؟',
        targetValue: 5,
        type: 'small-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤ خرزات للإشارة إلى ٤' },
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'ارفع خرزة إضافية = ٥' },
        ],
        explanation: '٤ + ١ = ٥',
      },
      {
        question: '٤ + ٣ = ؟',
        targetValue: 7,
        type: 'small-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤ خرزات' },
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'صديق ٣ هو ٢. أنزل العلوية (٥) وارفع ٢ سفليّة (٥ - ٢ = ٣)' },
        ],
        explanation: '٤ + ٣ = ٧. صديق ٣ هو ٢',
      },
      {
        question: '٣ + ٤ = ؟',
        targetValue: 7,
        type: 'small-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 3, finger: 'thumb', explanation: 'ارفع ٣ خرزات' },
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'صديق ٤ هو ١. أنزل العلوية (٥) وارفع ١ سفليّة' },
        ],
        explanation: '٣ + ٤ = ٧',
      },
      {
        question: '٢ + ٤ = ؟',
        targetValue: 6,
        type: 'small-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع خرزتين' },
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'صديق ٤ هو ١. أنزل العلوية + ١ سفليّة' },
        ],
        explanation: '٢ + ٤ = ٦',
      },
    ],  {
    id: 9,
    title: 'Adding 10',
    titleAr: 'الجمع مع أصدقاء 10',
    description: 'Carry to tens column',
    descriptionAr: 'احمل إلى عمود العشرات',
    status: 'locked',
    beads: { upper: 1, lower: 2 },
    value: 12,
    concept: '7 + 5 = 12',
    conceptAr: 'عند تجاوز الجمع ٩، احمل ١٠ إلى العمود التالي',
    icon: 'Plus',
    audioText: 'عندما يتجاوز الجمع الرقم تسعة، نحمل عشرة إلى العمود التالي. مثلاً، سبعة زائد خمسة يساوي اثنا عشر. صديق ٥ هو ٥، أي ١٠ - ٥ = ٥. نضيف ١٠ في العشرات ونطرح ٥ من الآحاد. هيا نجرب!',
    rule: 'Big Friend: if adding N exceeds 9, add 10 and subtract (10 - N)',
    ruleAr: 'صديق كبير: إذا تجاوز الجمع ٩، أضف ١٠ واطرح (١٠ - N)',
    examples: [
      {
        question: '٥ + ٥ = ؟',
        targetValue: 10,
        type: 'big-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 5, finger: 'thumb', explanation: 'ارفع ٥ = ٥' },
          { movement: 'pinch', upperBead: true, lowerBeads: 0, finger: 'both', explanation: 'صديق ٥ هو ٥: أضف ١٠ في العشرات، اطرح ٥ من الآحاد' },
        ],
        explanation: '٥ + ٥ = ١٠',
      },
      {
        question: '٦ + ٥ = ؟',
        targetValue: 11,
        type: 'big-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'مثّل ٦' },
          { movement: 'big-friend', upperBead: true, lowerBeads: 0, finger: 'both', explanation: 'صديق ٥ هو ٥: أضف ١٠، اطرح ٥ من الآحاد' },
        ],
        explanation: '٦ + ٥ = ١١',
      },
      {
        question: '٧ + ٥ = ؟',
        targetValue: 12,
        type: 'big-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'مثّل ٧' },
          { movement: 'big-friend', upperBead: true, lowerBeads: 0, finger: 'both', explanation: 'صديق ٥: أضف ١٠، اطرح ٥' },
        ],
        explanation: '٧ + ٥ = ١٢',
      },
      {
        question: '٨ + ٥ = ؟',
        targetValue: 13,
        type: 'big-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 3, finger: 'both', explanation: 'مثّل ٨' },
          { movement: 'big-friend', upperBead: true, lowerBeads: 0, finger: 'both', explanation: 'صديق ٥: أضف ١٠، اطرح ٥' },
        ],
        explanation: '٨ + ٥ = ١٣',
      },
      {
        question: '٩ + ٥ = ؟',
        targetValue: 14,
        type: 'big-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 4, finger: 'both', explanation: 'مثّل ٩' },
          { movement: 'big-friend', upperBead: true, lowerBeads: 0, finger: 'both', explanation: 'صديق ٥: أضف ١٠، اطرح ٥' },
        ],
        explanation: '٩ + ٥ = ١٤',
      },
    ],
  },
  {
    id: 10,
    title: 'Simple Subtraction',
    titleAr: 'الطرح البسيط',
    description: 'Remove beads',
    descriptionAr: 'أزل الخرزات لإتمام عملية الطرح',
    status: 'locked',
    beads: { upper: 0, lower: 3 },
    value: 3,
    concept: '5 - 2 = 3',
    conceptAr: 'أزل خرزات سفلية مباشرة بالسبابة',
    icon: 'Minus',
    audioText: 'الآن سنتعلم الطرح البسيط. عندما نطرح، ننزل الخرزات السفلية بالسبابة. مثلاً، خمسة ناقص اثنين يساوي ثلاثة. هيا نجرب!',
    rule: 'Use index finger to lower/remove lower beads',
    ruleAr: 'السبابة تنزل الخرزات السفلية عند الطرح',
    examples: [
      {
        question: '٥ - ١ = ؟',
        targetValue: 4,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'ارفع ١ للإشارة إلى ٥' },
          { movement: 'raise-lower', lowerBeads: 1, finger: 'index', explanation: 'أنزل خرزة واحدة بالسبابة' },
        ],
        explanation: '٥ - ١ = ٤',
      },
      {
        question: '٥ - ٢ = ؟',
        targetValue: 3,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 5, finger: 'thumb', explanation: 'مثّل ٥' },
          { movement: 'raise-lower', lowerBeads: 2, finger: 'index', explanation: 'أنزل خرزتين بالسبابة' },
        ],
        explanation: '٥ - ٢ = ٣',
      },
      {
        question: '٦ - ٣ = ؟',
        targetValue: 3,
        type: 'direct',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'مثّل ٦' },
          { movement: 'raise-lower', lowerBeads: 3, finger: 'index', explanation: 'أنزل ٣ خرزات بالسبابة' },
        ],
        explanation: '٦ - ٣ = ٣',
      },
      {
        question: '٩ - ٥ = ؟',
        targetValue: 4,
        type: 'small-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 4, finger: 'both', explanation: 'مثّل ٩' },
          { movement: 'raise-lower', upperBead: false, finger: 'index', explanation: 'صديق ٥: ارفع العلوية بالسبابة، ارجع ٤ سفليّة؟ (يحتاج شرح)' },
        ],
        explanation: '٩ - ٥ = ٤. اطرح ٥ مباشرة من العلوية',
      },
    ],
  },
  {
    id: 11,
    title: 'Subtracting 5',
    titleAr: 'الطرح مع أصدقاء 5',
    description: 'Use upper bead to subtract',
    descriptionAr: 'استخدم الخرزة العلوية في الطرح',
    status: 'locked',
    beads: { upper: 0, lower: 4 },
    value: 4,
    concept: '7 - 3 = 4',
    conceptAr: 'أحياناً نحتاج لإزالة ٥ وإرجاع الباقي',
    icon: 'Minus',
    audioText: 'أحياناً عندما نطرح، نحتاج لإزالة الخرزة العلوية وإرجاع الباقي. مثلاً، سبعة ناقص ثلاثة. صديق ٣ هو ٢: نرفع الخرزة العلوية بالسبابة و نرفع ٢ سفليّة بالإبهام (٥ - ٣ = ٢). هيا نجرب!',
    rule: 'Small Friend Subtraction: remove 5, add back (5 - N) lower beads',
    ruleAr: 'الطرح مع صديق 5: أزل العلوية (٥)، ثم أضف (٥ - N) سفليّة',
    examples: [
      {
        question: '٧ - ٣ = ؟',
        targetValue: 4,
        type: 'small-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'مثّل ٧' },
          { movement: 'open', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'صديق ٣ هو ٢: ارفع العلوية + ارفع ٢ سفليّة' },
        ],
        explanation: '٧ - ٣ = ٤. صديق ٣ هو ٢',
      },
      {
        question: '٨ - ٤ = ؟',
        targetValue: 4,
        type: 'small-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 3, finger: 'both', explanation: 'مثّل ٨' },
          { movement: 'open', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'صديق ٤ هو ١: ارفع العلوية + ارفع ١ سفليّة' },
        ],
        explanation: '٨ - ٤ = ٤',
      },
      {
        question: '٦ - ٢ = ؟',
        targetValue: 4,
        type: 'small-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'مثّل ٦' },
          { movement: 'open', upperBead: true, lowerBeads: 3, finger: 'both', explanation: 'صديق ٢ هو ٣: ارفع العلوية + ارفع ٣ سفليّة' },
        ],
        explanation: '٦ - ٢ = ٤',
      },
    ],
  },
  {
    id: 12,
    title: 'Subtracting 10',
    titleAr: 'الطرح مع أصدقاء 10',
    description: 'Borrow from tens column',
    descriptionAr: 'استلف من عمود العشرات',
    status: 'locked',
    beads: { upper: 0, lower: 2 },
    value: 7,
    concept: '12 - 5 = 7',
    conceptAr: 'عند طرح رقم أكبر، استلف ١٠ من العمود التالي',
    icon: 'Minus',
    audioText: 'عندما نطرح رقماً أكبر من المتوفر، نستلف عشرة من العمود التالي. مثلاً، اثنا عشر ناقص خمسة يساوي سبعة. صديق ٥ هو ٥: اطرح ١٠، ثم أضف ٥. هيا نجرب!',
    rule: 'Big Friend Subtraction: subtract 10, add back (10 - N)',
    ruleAr: 'صديق كبير: اطرح ١٠، ثم أضف (١٠ - N)',
    examples: [
      {
        question: '١٠ - ٣ = ؟',
        targetValue: 7,
        type: 'big-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'مثّل ١٠ (خرزة في العشرات)' },
          { movement: 'big-friend', lowerBeads: 7, finger: 'both', explanation: 'صديق ٣ هو ٧: اطرح ١٠، أضف ٧' },
        ],
        explanation: '١٠ - ٣ = ٧',
      },
      {
        question: '١٢ - ٥ = ؟',
        targetValue: 7,
        type: 'big-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'مثّل ١٠' },
          { movement: 'pinch', upperBead: true, lowerBeads: 2, finger: 'both', explanation: 'مثّل ١٢' },
          { movement: 'big-friend', lowerBeads: 5, finger: 'both', explanation: 'صديق ٥: اطرح ١٠، أضف ٥' },
        ],
        explanation: '١٢ - ٥ = ٧',
      },
      {
        question: '١٥ - ٧ = ؟',
        targetValue: 8,
        type: 'big-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'مثّل ١٠' },
          { movement: 'pinch', upperBead: true, lowerBeads: 0, finger: 'both', explanation: 'مثّل ١٥' },
          { movement: 'big-friend', lowerBeads: 3, finger: 'both', explanation: 'صديق ٧ هو ٣: اطرح ١٠، أضف ٣' },
        ],
        explanation: '١٥ - ٧ = ٨',
      },
    ],
  },
  {
    id: 13,
    title: 'Simple Multiplication',
    titleAr: 'الضرب البسيط',
    description: 'Repeated addition',
    descriptionAr: 'اضرب باستخدام الجمع المتكرر',
    status: 'locked',
    beads: { upper: 0, lower: 6 },
    value: 6,
    concept: '2 × 3 = 6',
    conceptAr: 'الضرب هو جمع متكرر: ٢ × ٣ = ٢ + ٢ + ٢ = ٦',
    icon: 'X',
    audioText: 'الضرب هو جمع متكرر. مثلاً، اثنان في ثلاثة تعني اثنان زائد اثنان زائد اثنان، وتساوي ستة. هيا نجرب!',
    rule: 'Multiplication is repeated addition',
    ruleAr: 'الضرب = جمع متكرر',
    examples: [
      {
        question: '٢ × ٢ = ؟',
        targetValue: 4,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع ٢ (٢ الأولى)' },
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع ٢ (٢ الثانية)' },
        ],
        explanation: '٢ × ٢ = ٤',
      },
      {
        question: '٢ × ٣ = ؟',
        targetValue: 6,
        type: 'pinch',
        steps: [
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤ (٢+٢)' },
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'أضف ٢ (أنزل العلوية وارفع ١)' },
        ],
        explanation: '٢ × ٣ = ٦',
      },
      {
        question: '٢ × ٤ = ؟',
        targetValue: 8,
        type: 'pinch',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 1, finger: 'both', explanation: 'مثّل ٦' },
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'أضف ٢' },
        ],
        explanation: '٢ × ٤ = ٨',
      },
      {
        question: '٢ × ٥ = ؟',
        targetValue: 10,
        type: 'big-friend',
        steps: [
          { movement: 'pinch', upperBead: true, lowerBeads: 4, finger: 'both', explanation: 'مثّل ٩' },
          { movement: 'big-friend', upperBead: false, lowerBeads: 0, finger: 'both', explanation: 'أضف ١: احمل ١٠ إلى العشرات، اطرح ٩' },
        ],
        explanation: '٢ × ٥ = ١٠',
      },
    ],
  },
  {
    id: 14,
    title: 'Multiplication Table 5',
    titleAr: 'جدول ضرب 5',
    description: 'Learn 5 times table',
    descriptionAr: 'تعلم جدول ضرب ٥',
    status: 'locked',
    beads: { upper: 1, lower: 0 },
    value: 15,
    concept: '5 × 3 = 15',
    conceptAr: 'جدول ضرب ٥',
    icon: 'X',
    audioText: 'الآن سنتعلم جدول ضرب الخمسة. خمسة في واحد يساوي خمسة، خمسة في اثنين يساوي عشرة، خمسة في ثلاثة يساوي خمسة عشر. هيا نجرب!',
    rule: '5 times table = adding 5 repeatedly',
    ruleAr: 'جدول ضرب ٥ = إضافة ٥ متكررة',
    examples: [
      {
        question: '٥ × ١ = ؟',
        targetValue: 5,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', upperBead: true, finger: 'index', explanation: 'أنزل العلوية = ٥' },
        ],
        explanation: '٥ × ١ = ٥',
      },
      {
        question: '٥ × ٢ = ؟',
        targetValue: 10,
        type: 'big-friend',
        steps: [
          { movement: 'raise-lower', upperBead: true, finger: 'index', explanation: 'مثّل ٥' },
          { movement: 'big-friend', upperBead: false, lowerBeads: 0, finger: 'both', explanation: 'أضف ٥: احمل ١٠، اطرح ٥' },
        ],
        explanation: '٥ × ٢ = ١٠',
      },
      {
        question: '٥ × ٣ = ؟',
        targetValue: 15,
        type: 'big-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'مثّل ١٠' },
          { movement: 'raise-lower', upperBead: true, finger: 'index', explanation: 'مثّل ٥ إضافية' },
        ],
        explanation: '٥ × ٣ = ١٥',
      },
      {
        question: '٥ × ٤ = ؟',
        targetValue: 20,
        type: 'big-friend',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'مثّل ٢٠ مباشرة (٢ في العشرات)' },
        ],
        explanation: '٥ × ٤ = ٢٠',
      },
    ],
  },
  {
    id: 15,
    title: 'Simple Division',
    titleAr: 'القسمة البسيطة',
    description: 'Divide into groups',
    descriptionAr: 'اقسم إلى مجموعات متساوية',
    status: 'locked',
    beads: { upper: 0, lower: 3 },
    value: 3,
    concept: '6 ÷ 2 = 3',
    conceptAr: 'القسمة تقسم إلى مجموعات متساوية',
    icon: 'Divide',
    audioText: 'القسمة تعني تقسيم العدد إلى مجموعات متساوية. مثلاً، ستة قسمة اثنين. هيا نجرب!',
    rule: 'Division = splitting into equal groups',
    ruleAr: 'القسمة = التقسيم إلى مجموعات متساوية',
    examples: [
      {
        question: '٤ ÷ ٢ = ؟',
        targetValue: 2,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع ٢ (النتيجة)' },
        ],
        explanation: '٤ ÷ ٢ = ٢',
      },
      {
        question: '٦ ÷ ٢ = ؟',
        targetValue: 3,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 3, finger: 'thumb', explanation: 'ارفع ٣ (النتيجة)' },
        ],
        explanation: '٦ ÷ ٢ = ٣',
      },
      {
        question: '٨ ÷ ٢ = ؟',
        targetValue: 4,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤' },
        ],
        explanation: '٨ ÷ ٢ = ٤',
      },
      {
        question: '١٠ ÷ ٢ = ؟',
        targetValue: 5,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', upperBead: true, finger: 'index', explanation: 'أنزل العلوية = ٥' },
        ],
        explanation: '١٠ ÷ ٢ = ٥',
      },
    ],
  },
  {
    id: 16,
    title: 'Division by 5',
    titleAr: 'القسمة على 5',
    description: 'Dividing by 5',
    descriptionAr: 'القسمة على العدد ٥',
    status: 'locked',
    beads: { upper: 0, lower: 2 },
    value: 2,
    concept: '10 ÷ 5 = 2',
    conceptAr: 'القسمة على ٥',
    icon: 'Divide',
    audioText: 'الآن سنتعلم القسمة على خمسة. عشرة قسمة خمسة تساوي اثنين، خمسة عشر قسمة خمسة تساوي ثلاثة. هيا نجرب!',
    rule: 'Division by 5',
    ruleAr: 'القسمة على ٥',
    examples: [
      {
        question: '٥ ÷ ٥ = ؟',
        targetValue: 1,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 1, finger: 'thumb', explanation: 'ارفع ١' },
        ],
        explanation: '٥ ÷ ٥ = ١',
      },
      {
        question: '١٠ ÷ ٥ = ؟',
        targetValue: 2,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 2, finger: 'thumb', explanation: 'ارفع ٢' },
        ],
        explanation: '١٠ ÷ ٥ = ٢',
      },
      {
        question: '١٥ ÷ ٥ = ؟',
        targetValue: 3,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 3, finger: 'thumb', explanation: 'ارفع ٣' },
        ],
        explanation: '١٥ ÷ ٥ = ٣',
      },
      {
        question: '٢٠ ÷ ٥ = ؟',
        targetValue: 4,
        type: 'direct',
        steps: [
          { movement: 'raise-lower', lowerBeads: 4, finger: 'thumb', explanation: 'ارفع ٤' },
        ],
        explanation: '٢٠ ÷ ٥ = ٤',
      },
    ],
  },
];

export const QUESTS: Quest[] = [
  { id: 1, title: 'Daily Practice', titleAr: 'التدريب اليومي', description: 'Complete 10 practice', descriptionAr: 'أكمل ١٠ مسائل تدريبية', xpReward: 50, progress: 0, target: 10, icon: 'Swords', color: 'from-purple-500 to-electric-500', type: 'practice' },
  { id: 2, title: 'Anzan Apprentice', titleAr: 'متدرب الأنزان', description: 'Score 20 points', descriptionAr: 'احصل على ٢٠ نقطة في الأنزان', xpReward: 80, progress: 0, target: 20, icon: 'Eye', color: 'from-electric-500 to-emerald2-500', type: 'anzan' },
  { id: 3, title: 'Perfect Streak', titleAr: 'سلسلة مثالية', description: 'Maintain 5-day streak', descriptionAr: 'حافظ على سلسلة ٥ أيام', xpReward: 100, progress: 0, target: 5, icon: 'Flame', color: 'from-gold-400 to-gold-600', type: 'streak' },
  { id: 4, title: 'Lesson Explorer', titleAr: 'مستكشف الدروس', description: 'Complete 3 lessons', descriptionAr: 'أكمل ٣ وحدات تعليمية', xpReward: 60, progress: 0, target: 3, icon: 'BookOpen', color: 'from-emerald2-400 to-emerald2-600', type: 'lessons' },
  { id: 5, title: 'Addition Master', titleAr: 'سيد الجمع', description: '5 additions', descriptionAr: 'أكمل ٥ مسائل جمع', xpReward: 70, progress: 0, target: 5, icon: 'Plus', color: 'from-purple-400 to-purple-600', type: 'addition' },
  { id: 6, title: 'Subtraction Hero', titleAr: 'بطل الطرح', description: '5 subtractions', descriptionAr: 'أكمل ٥ مسائل طرح', xpReward: 70, progress: 0, target: 5, icon: 'Minus', color: 'from-electric-400 to-electric-600', type: 'subtraction' },
  { id: 7, title: 'Multiplication Pro', titleAr: 'محترف الضرب', description: '5 multiplications', descriptionAr: 'أكمل ٥ مسائل ضرب', xpReward: 100, progress: 0, target: 5, icon: 'X', color: 'from-pink-400 to-pink-600', type: 'multiplication' },
  { id: 8, title: 'Division Expert', titleAr: 'خبير القسمة', description: '5 divisions', descriptionAr: 'أكمل ٥ مسائل قسمة', xpReward: 100, progress: 0, target: 5, icon: 'Divide', color: 'from-gold-400 to-gold-600', type: 'division' },
  { id: 9, title: 'Anzan Expert', titleAr: 'خبير الأنزان', description: 'Score 50 points', descriptionAr: 'احصل على ٥٠ نقطة في الأنزان', xpReward: 150, progress: 0, target: 50, icon: 'Eye', color: 'from-emerald2-400 to-emerald2-600', type: 'anzanHighScore' },
];

export const ADDITION_QUESTIONS: PracticeQuestion[] = [
  { question: '٢ + ٣', answer: 5, choices: [4, 5, 6, 7], type: 'direct' },
  { question: '٣ + ٢', answer: 5, choices: [4, 5, 6, 7], type: 'direct' },
  { question: '٤ + ٢', answer: 6, choices: [5, 6, 7, 8], type: 'pinch' },
  { question: '٢ + ٤', answer: 6, choices: [5, 6, 7, 8], type: 'pinch' },
  { question: '٥ + ٢', answer: 7, choices: [6, 7, 8, 9], type: 'pinch' },
  { question: '٣ + ٤', answer: 7, choices: [6, 7, 8, 9], type: 'small-friend' },
  { question: '٤ + ٤', answer: 8, choices: [7, 8, 9, 10], type: 'small-friend' },
  { question: '٦ + ٢', answer: 8, choices: [7, 8, 9, 10], type: 'pinch' },
  { question: '٥ + ٤', answer: 9, choices: [8, 9, 10, 11], type: 'small-friend' },
  { question: '٣ + ٦', answer: 9, choices: [8, 9, 10, 11], type: 'small-friend' },
  { question: '٥ + ٥', answer: 10, choices: [9, 10, 11, 12], type: 'big-friend' },
  { question: '٦ + ٥', answer: 11, choices: [10, 11, 12, 13], type: 'big-friend' },
  { question: '٧ + ٥', answer: 12, choices: [11, 12, 13, 14], type: 'big-friend' },
  { question: '٨ + ٥', answer: 13, choices: [12, 13, 14, 15], type: 'big-friend' },
  { question: '٩ + ٥', answer: 14, choices: [13, 14, 15, 16], type: 'big-friend' },
];

export const SUBTRACTION_QUESTIONS: PracticeQuestion[] = [
  { question: '٥ - ١', answer: 4, choices: [3, 4, 5, 6], type: 'direct' },
  { question: '٦ - ١', answer: 5, choices: [4, 5, 6, 7], type: 'direct' },
  { question: '٧ - ٢', answer: 5, choices: [4, 5, 6, 7], type: 'small-friend' },
  { question: '٧ - ٣', answer: 4, choices: [3, 4, 5, 6], type: 'small-friend' },
  { question: '٨ - ٣', answer: 5, choices: [4, 5, 6, 7], type: 'small-friend' },
  { question: '٩ - ٣', answer: 6, choices: [5, 6, 7, 8], type: 'small-friend' },
  { question: '٩ - ٥', answer: 4, choices: [3, 4, 5, 6], type: 'direct' },
  { question: '٨ - ٥', answer: 3, choices: [2, 3, 4, 5], type: 'direct' },
  { question: '٧ - ٥', answer: 2, choices: [1, 2, 3, 4], type: 'direct' },
  { question: '١٠ - ٣', answer: 7, choices: [6, 7, 8, 9], type: 'big-friend' },
  { question: '١٢ - ٤', answer: 8, choices: [7, 8, 9, 10], type: 'big-friend' },
  { question: '١٣ - ٥', answer: 8, choices: [7, 8, 9, 10], type: 'big-friend' },
  { question: '١٥ - ٧', answer: 8, choices: [7, 8, 9, 10], type: 'big-friend' },
  { question: '١١ - ٥', answer: 6, choices: [5, 6, 7, 8], type: 'big-friend' },
];

export const MULTIPLICATION_QUESTIONS: PracticeQuestion[] = [
  { question: '١ × ٢', answer: 2, choices: [1, 2, 3, 4] },
  { question: '٢ × ٢', answer: 4, choices: [3, 4, 5, 6] },
  { question: '٣ × ٢', answer: 6, choices: [5, 6, 7, 8] },
  { question: '٤ × ٢', answer: 8, choices: [7, 8, 9, 10] },
  { question: '٥ × ٢', answer: 10, choices: [9, 10, 11, 12] },
  { question: '٢ × ٣', answer: 6, choices: [5, 6, 7, 8] },
  { question: '٣ × ٣', answer: 9, choices: [8, 9, 10, 11] },
  { question: '٤ × ٣', answer: 12, choices: [11, 12, 13, 14] },
  { question: '٢ × ٤', answer: 8, choices: [7, 8, 9, 10] },
  { question: '٣ × ٤', answer: 12, choices: [11, 12, 13, 14] },
  { question: '٢ × ٥', answer: 10, choices: [9, 10, 11, 12] },
  { question: '٣ × ٥', answer: 15, choices: [14, 15, 16, 17] },
  { question: '٤ × ٥', answer: 20, choices: [19, 20, 21, 22] },
  { question: '٢ × ٦', answer: 12, choices: [11, 12, 13, 14] },
  { question: '٣ × ٦', answer: 18, choices: [17, 18, 19, 20] },
  { question: '٢ × ٧', answer: 14, choices: [13, 14, 15, 16] },
  { question: '٢ × ٨', answer: 16, choices: [15, 16, 17, 18] },
  { question: '٢ × ٩', answer: 18, choices: [17, 18, 19, 20] },
  { question: '٣ × ٧', answer: 21, choices: [20, 21, 22, 23] },
  { question: '٣ × ٨', answer: 24, choices: [23, 24, 25, 26] },
];

export const DIVISION_QUESTIONS: PracticeQuestion[] = [
  { question: '٤ ÷ ٢', answer: 2, choices: [1, 2, 3, 4] },
  { question: '٦ ÷ ٢', answer: 3, choices: [2, 3, 4, 5] },
  { question: '٨ ÷ ٢', answer: 4, choices: [3, 4, 5, 6] },
  { question: '١٠ ÷ ٢', answer: 5, choices: [4, 5, 6, 7] },
  { question: '١٢ ÷ ٢', answer: 6, choices: [5, 6, 7, 8] },
  { question: '٦ ÷ ٣', answer: 2, choices: [1, 2, 3, 4] },
  { question: '٩ ÷ ٣', answer: 3, choices: [2, 3, 4, 5] },
  { question: '١٢ ÷ ٣', answer: 4, choices: [3, 4, 5, 6] },
  { question: '١٥ ÷ ٣', answer: 5, choices: [4, 5, 6, 7] },
  { question: '٨ ÷ ٤', answer: 2, choices: [1, 2, 3, 4] },
  { question: '١٢ ÷ ٤', answer: 3, choices: [2, 3, 4, 5] },
  { question: '١٦ ÷ ٤', answer: 4, choices: [3, 4, 5, 6] },
  { question: '٢٠ ÷ ٤', answer: 5, choices: [4, 5, 6, 7] },
  { question: '١٠ ÷ ٥', answer: 2, choices: [1, 2, 3, 4] },
  { question: '١٥ ÷ ٥', answer: 3, choices: [2, 3, 4, 5] },
  { question: '٢٠ ÷ ٥', answer: 4, choices: [3, 4, 5, 6] },
  { question: '٢٥ ÷ ٥', answer: 5, choices: [4, 5, 6, 7] },
  { question: '١٢ ÷ ٦', answer: 2, choices: [1, 2, 3, 4] },
  { question: '١٨ ÷ ٦', answer: 3, choices: [2, 3, 4, 5] },
  { question: '٢١ ÷ ٧', answer: 3, choices: [2, 3, 4, 5] },
];

export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  ...ADDITION_QUESTIONS,
  ...SUBTRACTION_QUESTIONS,
  ...MULTIPLICATION_QUESTIONS,
  ...DIVISION_QUESTIONS,
];

export const PROGRESS_DATA: ProgressData = {
  totalProblems: 0, correctAnswers: 0, averageSpeed: 0, lessonsCompleted: 0, anzanHighScore: 0,
  weeklyXP: [{ day: 'السبت', xp: 0 }, { day: 'الأحد', xp: 0 }, { day: 'الاثنين', xp: 0 }, { day: 'الثلاثاء', xp: 0 }, { day: 'الأربعاء', xp: 0 }, { day: 'الخميس', xp: 0 }, { day: 'الجمعة', xp: 0 }],
};

export const BADGES = [
  { id: 'beginner', name: 'Beginner', nameAr: 'مبتدئ', xpRequired: 200, icon: 'Star' },
  { id: 'trainee', name: 'Trainee', nameAr: 'متدرب', xpRequired: 500, icon: 'Target' },
  { id: 'anzan-master', name: 'Anzan Master', nameAr: 'سيد الأنزان', xpRequired: 750, icon: 'Eye' },
  { id: 'skilled', name: 'Skilled', nameAr: 'ماهر', xpRequired: 1250, icon: 'Award' },
  { id: 'soroban-expert', name: 'Soroban Expert', nameAr: 'خبير السوروبان', xpRequired: 2000, icon: 'Award' },
  { id: 'professional', name: 'Professional', nameAr: 'محترف', xpRequired: 3500, icon: 'Diamond' },
  { id: 'legend', name: 'Legend', nameAr: 'أسطورة', xpRequired: 5000, icon: 'Crown' },
  { id: 'eternal-legend', name: 'Eternal Legend', nameAr: 'أسطورة خالدة', xpRequired: 10000, icon: 'Crown' },
];
  },
];
